server:
  port: 9001
  servlet:
    context-path: /recode

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug

spring:
  # import application-local.yml
  profiles:
    include: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB