# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.chebyqrxrs5q.ap-northeast-2.rds.amazonaws.com:3306/dub?serverTimezone=UTC&characterEncoding=UTF-8
    username: dub
    password:

# S3 Setting
#cloud:
#  aws:
#    credentials:
#      accessKey:       # AWS IAM AccessKey 적기
#      secretKey:    # AWS IAM SecretKey 적기
#    s3:
#      bucket:  # 버킷 이름
#      dir:  # s3 디렉토리 이름
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false